### PR TITLE
add stage2 model and views

### PR DESCRIPTION
**Pull request by gorserg**
Добавлена логіка по другому етапу (model та views)
Залежить (поки) від 
https://github.com/openprocurement/openprocurement.api/pull/96

---
This change is [Reviewable](https://reviewable.io/reviews/openprocurement/openprocurement.tender.competitivedialogue/8)

### CODE REVIEW

**Comment by kroman0** [comment]
Reviewed 4 of 5 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[setup.py, line 25 \[r2\]](https://reviewable.io:443/reviews/openprocurement/openprocurement.tender.competitivedialogue/8#-KLX00pPMvVTSoWYUkl8:-KLX00pPMvVTSoWYUkl9:-1326323412) ([raw file](https://github.com/openprocurement/openprocurement.tender.competitivedialogue/blob/7e8a942f76f554058c892d76f7a7d049f5ead23f/setup.py#L25)):*
> ```Python
>     'console_scripts': [
>         'competitive_dialogue_data_bridge = openprocurement.tender.competitivedialogue.databridge:main'
>     ],
> ```

це до  https://github.com/openprocurement/openprocurement.tender.competitivedialogue/pull/9

---

*[openprocurement/tender/competitivedialogue/models.py, line 23 \[r2\]](https://reviewable.io:443/reviews/openprocurement/openprocurement.tender.competitivedialogue/8#-KLX0MHqsB4eXZk64di-:-KLX0MHqsB4eXZk64di0:-971324113) ([raw file](https://github.com/openprocurement/openprocurement.tender.competitivedialogue/blob/7e8a942f76f554058c892d76f7a7d049f5ead23f/openprocurement/tender/competitivedialogue/models.py#L23)):*
> ```Python
> CD_UA_TYPE = "competitiveDialogueUA"
> CD_EU_TYPE = "competitiveDialogueEU"
> STAGE_2_EU_TYPE = "aboveThresholdEU.stage2"
> ```

competitiveDialogueUA.stage2 і competitiveDialogueEU.stage2 було б логічніше, можете пояснити такий вибір?

---

*[openprocurement/tender/competitivedialogue/models.py, line 40 \[r2\]](https://reviewable.io:443/reviews/openprocurement/openprocurement.tender.competitivedialogue/8#-KLX0jHLQW0Rbsk27s1U:-KLX0jHLQW0Rbsk27s1V:1364269760) ([raw file](https://github.com/openprocurement/openprocurement.tender.competitivedialogue/blob/7e8a942f76f554058c892d76f7a7d049f5ead23f/openprocurement/tender/competitivedialogue/models.py#L40)):*
> ```Python
>     'active.stage2.waiting': pre_qualifications_role,
>     'edit_active.stage2.pending': edit_stage2_pending,
>     'edit_active.stage2.waiting': edit_stage2_waiting,
> ```

Власник не мав би нічого міняти на `active.stage2.waiting`

---

*[openprocurement/tender/competitivedialogue/models.py, line 186 \[r2\]](https://reviewable.io:443/reviews/openprocurement/openprocurement.tender.competitivedialogue/8#-KLX3nrVLAm5WObTSHxN:-KLX3nrWNirlk3a-TIGF:-973485044) ([raw file](https://github.com/openprocurement/openprocurement.tender.competitivedialogue/blob/7e8a942f76f554058c892d76f7a7d049f5ead23f/openprocurement/tender/competitivedialogue/models.py#L186)):*
> ```Python
> class Tender(TenderEU):
>     procurementMethodType = StringType(default=STAGE_2_EU_TYPE)
>     dialogue_token = StringType(required=True)
> ```

dialogue_token потрібно приховати по ролях

---

*[openprocurement/tender/competitivedialogue/views/tender.py, line 58 \[r2\]](https://reviewable.io:443/reviews/openprocurement/openprocurement.tender.competitivedialogue/8#-KLX3BM37qirW5YUsrY2:-KLX3BM4Ek42Bx243Efi:-1650391328) ([raw file](https://github.com/openprocurement/openprocurement.tender.competitivedialogue/blob/7e8a942f76f554058c892d76f7a7d049f5ead23f/openprocurement/tender/competitivedialogue/views/tender.py#L58)):*
> ```Python
> 
> 
> @opresource(name='Tender stage2 credentials',
> ```

Це ресурс має бути для відповідних procurementMethodType

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/openprocurement.tender.competitivedialogue/8)*

**Comment by kroman0** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[openprocurement/tender/competitivedialogue/models.py, line 23 \[r2\]](https://reviewable.io:443/reviews/openprocurement/openprocurement.tender.competitivedialogue/8#-KLX0MHqsB4eXZk64di-:-KL_c7K0oyY8qEZY_FIG:166874) ([raw file](https://github.com/openprocurement/openprocurement.tender.competitivedialogue/blob/7e8a942f76f554058c892d76f7a7d049f5ead23f/openprocurement/tender/competitivedialogue/models.py#L23)):*
<details><summary><i>Previously, kroman0 (Roman Kozlovskyi) wrote…</i></summary>
> competitiveDialogueUA.stage2 і competitiveDialogueEU.stage2 було б логічніше, можете пояснити такий вибір?
</details>
?

---

*[openprocurement/tender/competitivedialogue/models.py, line 40 \[r2\]](https://reviewable.io:443/reviews/openprocurement/openprocurement.tender.competitivedialogue/8#-KLX0jHLQW0Rbsk27s1U:-KL_c4Fe3JmT-8on5eGD:5173665) ([raw file](https://github.com/openprocurement/openprocurement.tender.competitivedialogue/blob/7e8a942f76f554058c892d76f7a7d049f5ead23f/openprocurement/tender/competitivedialogue/models.py#L40)):*
<details><summary><i>Previously, kroman0 (Roman Kozlovskyi) wrote…</i></summary>
> Власник не мав би нічого міняти на `active.stage2.waiting`
</details>
OK

---

*[openprocurement/tender/competitivedialogue/views/tender.py, line 62 \[r3\]](https://reviewable.io:443/reviews/openprocurement/openprocurement.tender.competitivedialogue/8#-KL_ba4_DFdZnV2bxbDg:-KL_ba4_DFdZnV2bxbDh:-1529085199) ([raw file](https://github.com/openprocurement/openprocurement.tender.competitivedialogue/blob/915b5420f0c2395327ffe067667874d27747bcf3/openprocurement/tender/competitivedialogue/views/tender.py#L62)):*
> ```Python
>             procurementMethodType=STAGE_2_EU_TYPE,
>             description="Tender stage2 UE credentials")
> class TenderStage2EUCredentialsResource(TenderResource):
> ```

TenderResource приносить get якого тут не треба, тому треба використати APIResource

---

*[openprocurement/tender/competitivedialogue/views/tender.py, line 65 \[r3\]](https://reviewable.io:443/reviews/openprocurement/openprocurement.tender.competitivedialogue/8#-KL_bUF95l-gy-JdAwh5:-KL_bUF95l-gy-JdAwh6:120144424) ([raw file](https://github.com/openprocurement/openprocurement.tender.competitivedialogue/blob/915b5420f0c2395327ffe067667874d27747bcf3/openprocurement/tender/competitivedialogue/views/tender.py#L65)):*
> ```Python
>     def __init__(self, request, context):
>         super(TenderStage2EUCredentialsResource, self).__init__(request, context)
>         self.server = request.registry.couchdb_server
> ```

self.server не використовується

---

*[openprocurement/tender/competitivedialogue/views/tender.py, line 93 \[r3\]](https://reviewable.io:443/reviews/openprocurement/openprocurement.tender.competitivedialogue/8#-KL_bE-zk3T8vhv-BqPp:-KL_bE-zk3T8vhv-BqPq:1204090210) ([raw file](https://github.com/openprocurement/openprocurement.tender.competitivedialogue/blob/915b5420f0c2395327ffe067667874d27747bcf3/openprocurement/tender/competitivedialogue/views/tender.py#L93)):*
> ```Python
>             procurementMethodType=STAGE_2_UA_TYPE,
>             description="Tender stage2 UA credentials")
> class TenderStage2UACredentialsResource(TenderResource):
> ```

TenderStage2UACredentialsResource можна унаслідувати від TenderStage2EUCredentialsResource щоб не дублювати код

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/openprocurement.tender.competitivedialogue/8)*

**Comment by Krokop** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[openprocurement/tender/competitivedialogue/models.py, line 40 \[r2\]](https://reviewable.io:443/reviews/openprocurement/openprocurement.tender.competitivedialogue/8#-KLX0jHLQW0Rbsk27s1U:-KL_Z6eBoJGpmt7Wk9En:-18455389) ([raw file](https://github.com/openprocurement/openprocurement.tender.competitivedialogue/blob/7e8a942f76f554058c892d76f7a7d049f5ead23f/openprocurement/tender/competitivedialogue/models.py#L40)):*
<details><summary><i>Previously, kroman0 (Roman Kozlovskyi) wrote…</i></summary>
> Власник не мав би нічого міняти на `active.stage2.waiting`
</details>
Прибрав

---

*[openprocurement/tender/competitivedialogue/models.py, line 186 \[r2\]](https://reviewable.io:443/reviews/openprocurement/openprocurement.tender.competitivedialogue/8#-KLX3nrVLAm5WObTSHxN:-KL_ZCG7ezqcHh9Catgt:96729692) ([raw file](https://github.com/openprocurement/openprocurement.tender.competitivedialogue/blob/7e8a942f76f554058c892d76f7a7d049f5ead23f/openprocurement/tender/competitivedialogue/models.py#L186)):*
<details><summary><i>Previously, kroman0 (Roman Kozlovskyi) wrote…</i></summary>
> dialogue_token потрібно приховати по ролях
</details>
Додав ролі для роботи з другим етапом, приховав dialogue_token,  заборонив змінювати dialogue_token, dialogueID та shortlistedFirsm

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/openprocurement.tender.competitivedialogue/8)*

**Comment by Krokop** [comment]
*[openprocurement/tender/competitivedialogue/models.py, line 23 \[r2\]](https://reviewable.io:443/reviews/openprocurement/openprocurement.tender.competitivedialogue/8#-KLX0MHqsB4eXZk64di-:-KL_d4NKIelGBI2kvXtD:-1436663887) ([raw file](https://github.com/openprocurement/openprocurement.tender.competitivedialogue/blob/7e8a942f76f554058c892d76f7a7d049f5ead23f/openprocurement/tender/competitivedialogue/models.py#L23)):*
<details><summary><i>Previously, kroman0 (Roman Kozlovskyi) wrote…</i></summary>
> ?
</details>
Мы обрали таку назву, тому що логіка роботи другого етапу повністю відповідає логіці тендеру з відкритими торгами, за винятком деяких нюансів. Тому ми позичили частину назву procurementMethodType, але якщо ви наполягаете ми можемо її змінити.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/openprocurement.tender.competitivedialogue/8)*

**Comment by Krokop** [comment]
*[setup.py, line 25 \[r2\]](https://reviewable.io:443/reviews/openprocurement/openprocurement.tender.competitivedialogue/8#-KLX00pPMvVTSoWYUkl8:-KL_fh-IewqCeey_49Wu:676635175) ([raw file](https://github.com/openprocurement/openprocurement.tender.competitivedialogue/blob/7e8a942f76f554058c892d76f7a7d049f5ead23f/setup.py#L25)):*
<details><summary><i>Previously, kroman0 (Roman Kozlovskyi) wrote…</i></summary>
> це до  https://github.com/openprocurement/openprocurement.tender.competitivedialogue/pull/9
</details>
Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/openprocurement.tender.competitivedialogue/8)*

**Comment by Krokop** [comment]
Review status: 3 of 4 files reviewed at latest revision, 8 unresolved discussions.

---

*[openprocurement/tender/competitivedialogue/views/tender.py, line 58 \[r2\]](https://reviewable.io:443/reviews/openprocurement/openprocurement.tender.competitivedialogue/8#-KLX3BM37qirW5YUsrY2:-KL_n0Wxt4jckDd_ySYa:1540212626) ([raw file](https://github.com/openprocurement/openprocurement.tender.competitivedialogue/blob/7e8a942f76f554058c892d76f7a7d049f5ead23f/openprocurement/tender/competitivedialogue/views/tender.py#L58)):*
<details><summary><i>Previously, kroman0 (Roman Kozlovskyi) wrote…</i></summary>
> Це ресурс має бути для відповідних procurementMethodType
</details>
Додав procurementMethodType

---

*[openprocurement/tender/competitivedialogue/views/tender.py, line 62 \[r3\]](https://reviewable.io:443/reviews/openprocurement/openprocurement.tender.competitivedialogue/8#-KL_ba4_DFdZnV2bxbDg:-KL_nAKA90bAQP0A5OHT:-298651265) ([raw file](https://github.com/openprocurement/openprocurement.tender.competitivedialogue/blob/915b5420f0c2395327ffe067667874d27747bcf3/openprocurement/tender/competitivedialogue/views/tender.py#L62)):*
<details><summary><i>Previously, kroman0 (Roman Kozlovskyi) wrote…</i></summary>
> TenderResource приносить get якого тут не треба, тому треба використати APIResource
</details>
TenderStage2EUCredentialsResource наслідується від APIResource

---

*[openprocurement/tender/competitivedialogue/views/tender.py, line 65 \[r3\]](https://reviewable.io:443/reviews/openprocurement/openprocurement.tender.competitivedialogue/8#-KL_bUF95l-gy-JdAwh5:-KL_nOsGNK0PCL_AZE0z:496131693) ([raw file](https://github.com/openprocurement/openprocurement.tender.competitivedialogue/blob/915b5420f0c2395327ffe067667874d27747bcf3/openprocurement/tender/competitivedialogue/views/tender.py#L65)):*
<details><summary><i>Previously, kroman0 (Roman Kozlovskyi) wrote…</i></summary>
> self.server не використовується
</details>
Прибрав init

---

*[openprocurement/tender/competitivedialogue/views/tender.py, line 93 \[r3\]](https://reviewable.io:443/reviews/openprocurement/openprocurement.tender.competitivedialogue/8#-KL_bE-zk3T8vhv-BqPp:-KL_nRtR9H1fx5ewsNRd:1753336645) ([raw file](https://github.com/openprocurement/openprocurement.tender.competitivedialogue/blob/915b5420f0c2395327ffe067667874d27747bcf3/openprocurement/tender/competitivedialogue/views/tender.py#L93)):*
<details><summary><i>Previously, kroman0 (Roman Kozlovskyi) wrote…</i></summary>
> TenderStage2UACredentialsResource можна унаслідувати від TenderStage2EUCredentialsResource щоб не дублювати код
</details>
TenderStage2UACredentialsResource наслідується від TenderStage2EUCredentialsResource

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/openprocurement.tender.competitivedialogue/8)*

**Comment by kroman0** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[openprocurement/tender/competitivedialogue/models.py, line 23 \[r2\]](https://reviewable.io:443/reviews/openprocurement/openprocurement.tender.competitivedialogue/8#-KLX0MHqsB4eXZk64di-:-KL_ss5fpg54XxdKHVHr:84972108) ([raw file](https://github.com/openprocurement/openprocurement.tender.competitivedialogue/blob/7e8a942f76f554058c892d76f7a7d049f5ead23f/openprocurement/tender/competitivedialogue/models.py#L23)):*
<details><summary><i>Previously, Krokop (Oleg Serbokryl) wrote…</i></summary>
> Мы обрали таку назву, тому що логіка роботи другого етапу повністю відповідає логіці тендеру з відкритими торгами, за винятком деяких нюансів. Тому ми позичили частину назву procurementMethodType, але якщо ви наполягаете ми можемо її змінити.
</details>
З назви в такому випадку не зрозуміло що це конкурентний діалог. Можливо @myroslav має ще якусь думку.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/openprocurement.tender.competitivedialogue/8)*

**Comment by myroslav** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[openprocurement/tender/competitivedialogue/models.py, line 23 \[r2\]](https://reviewable.io:443/reviews/openprocurement/openprocurement.tender.competitivedialogue/8#-KLX0MHqsB4eXZk64di-:-KLan9aUtNLOglbRJwe3:-93345139) ([raw file](https://github.com/openprocurement/openprocurement.tender.competitivedialogue/blob/7e8a942f76f554058c892d76f7a7d049f5ead23f/openprocurement/tender/competitivedialogue/models.py#L23)):*
<details><summary><i>Previously, kroman0 (Roman Kozlovskyi) wrote…</i></summary>
> З назви в такому випадку не зрозуміло що це конкурентний діалог. Можливо @myroslav має ще якусь думку.
</details>
Пропоную варіант `aboveThresholdEU.competitiveDialogue` та `aboveThresholdUA.competitiveDialogue`, взагалі без вказання того, що це друга фаза, це дозволить вказати, на те, що відповідна процедура є підвидом відповідної, але адаптована до потреб конкурентного діалогу.

Також вважаю адекватними `competitiveDialogueUA.stage2` та `competitiveDialogueEU.stage2`, так як ми вже маємо відповідні перші фази.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/openprocurement.tender.competitivedialogue/8)*

**Comment by Krokop** [comment]
Review status: 3 of 4 files reviewed at latest revision, 7 unresolved discussions.

---

*[openprocurement/tender/competitivedialogue/models.py, line 23 \[r2\]](https://reviewable.io:443/reviews/openprocurement/openprocurement.tender.competitivedialogue/8#-KLX0MHqsB4eXZk64di-:-KLapguLokprEgKhWg7C:-819304149) ([raw file](https://github.com/openprocurement/openprocurement.tender.competitivedialogue/blob/7e8a942f76f554058c892d76f7a7d049f5ead23f/openprocurement/tender/competitivedialogue/models.py#L23)):*
<details><summary><i>Previously, myroslav (Myroslav Opyr) wrote…</i></summary>
> Пропоную варіант `aboveThresholdEU.competitiveDialogue` та `aboveThresholdUA.competitiveDialogue`, взагалі без вказання того, що це друга фаза, це дозволить вказати, на те, що відповідна процедура є підвидом відповідної, але адаптована до потреб конкурентного діалогу.
> 
> Також вважаю адекватними `competitiveDialogueUA.stage2` та `competitiveDialogueEU.stage2`, так як ми вже маємо відповідні перші фази.
</details>
competitiveDialogueUA.stage2  та competitiveDialogueEU.stage2 підходить для нас.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/openprocurement.tender.competitivedialogue/8)*

**Comment by kroman0** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/openprocurement.tender.competitivedialogue/8)*

**Comment by kroman0** [comment]
:lgtm: 
цей PR приймаємо але в наступному необхідно поправити покриття коду тестами

---

Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/openprocurement.tender.competitivedialogue/8#-:-KLaxkhWzFcNEIFMPvQO:-1625574723)*

**Pull request merged**
