### PR TITLE
Add new statuses active.waiting-stage2 and active.ready-stage2

### PR DESCRIPTION
**Pull request by gorserg**
Два нові статуси, логіку описували тут https://groups.google.com/forum/#!msg/open-procurement-dev/Pwb_usMTZK8/9ZusnBSjAgAJ

---
This change is [Reviewable](https://reviewable.io/reviews/openprocurement/openprocurement.tender.competitivedialogue/4)

### CODE REVIEW

**Comment by kroman0** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[openprocurement/tender/competitivedialogue/tests/base.py, line 253 \[r1\]](https://reviewable.io:443/reviews/openprocurement/openprocurement.tender.competitivedialogue/4#-KKOuDqpkDHr4pp1O5WS:-KKOuDqpkDHr4pp1O5WT:-203691255) ([raw file](https://github.com/openprocurement/openprocurement.tender.competitivedialogue/blob/2195e1046acafd38bfe126f49918beb51b3b3e51/openprocurement/tender/competitivedialogue/tests/base.py#L253)):*
> ```Python
>                     "endDate": (now).isoformat()
>                 },
>                 "auctionPeriod": {
> ```

Цього тут не треба для 'active.waiting-stage2'

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/openprocurement.tender.competitivedialogue/4)*

**Comment by gorserg** [comment]
*[openprocurement/tender/competitivedialogue/tests/base.py, line 253 \[r1\]](https://reviewable.io:443/reviews/openprocurement/openprocurement.tender.competitivedialogue/4#-KKOuDqpkDHr4pp1O5WS:-KKSw_NqqJC3HbYQyzZ8:-499146009) ([raw file](https://github.com/openprocurement/openprocurement.tender.competitivedialogue/blob/2195e1046acafd38bfe126f49918beb51b3b3e51/openprocurement/tender/competitivedialogue/tests/base.py#L253)):*
<details><summary><i>Previously, kroman0 (Roman Kozlovskyi) wrote…</i></summary>
> Цього тут не треба для 'active.waiting-stage2'
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/openprocurement.tender.competitivedialogue/4)*

**Comment by gorserg** [comment]
змінено назви статусів (по рекомендації Мирослава)
active.waiting-stage2 -> active.stage2.pending
active.ready-stage2 -> active.stage2.waiting

**Comment by kroman0** [comment]
Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/openprocurement.tender.competitivedialogue/4)*

**Pull request merged**
