### PR TITLE
Add bid views

### PR DESCRIPTION
**Pull request by Krokop**
Поки без покриття тестами із-за проблем з пам'яттю https://github.com/openprocurement/openprocurement.tender.competitivedialogue/pull/16

---
This change is [Reviewable](https://reviewable.io/reviews/openprocurement/openprocurement.tender.competitivedialogue/17)

### CODE REVIEW

**Comment by kroman0** [comment]
Reviewed 1 of 2 files at r1, 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[openprocurement/tender/competitivedialogue/utils.py, line 237 \[r3\]](https://reviewable.io:443/reviews/openprocurement/openprocurement.tender.competitivedialogue/17#-KMj0R7uCJodzwm9mBiH:-KMj0R7uCJodzwm9mBiI:408263150) ([raw file](https://github.com/openprocurement/openprocurement.tender.competitivedialogue/blob/c66437de804f517c5223ed8df43c7d714b3177b6/openprocurement/tender/competitivedialogue/utils.py#L237)):*
> ```Python
>         return
>     data = self.request.validated['data']
>     firm_keys = prepare_shortlistedFirms(tender.shortlistedFirms)
> ```

В цих функціях доцільніше віддавати set і перевіряти set пропозиції до set переліку з 1 стадії.

---

*[openprocurement/tender/competitivedialogue/utils.py, line 238 \[r3\]](https://reviewable.io:443/reviews/openprocurement/openprocurement.tender.competitivedialogue/17#-KMj-yoiL3nC1NjnxpUa:-KMj-yoiL3nC1NjnxpUb:1429760052) ([raw file](https://github.com/openprocurement/openprocurement.tender.competitivedialogue/blob/c66437de804f517c5223ed8df43c7d714b3177b6/openprocurement/tender/competitivedialogue/utils.py#L238)):*
> ```Python
>     data = self.request.validated['data']
>     firm_keys = prepare_shortlistedFirms(tender.shortlistedFirms)
>     bid_keys = prepare_bid_identifier(data)
> ```

можливо краще використати self.request.validated['bid']?

---

*[openprocurement/tender/competitivedialogue/utils.py, line 240 \[r3\]](https://reviewable.io:443/reviews/openprocurement/openprocurement.tender.competitivedialogue/17#-KMj1-hKAh_VAZMviYqf:-KMj1-hKAh_VAZMviYqg:580087189) ([raw file](https://github.com/openprocurement/openprocurement.tender.competitivedialogue/blob/c66437de804f517c5223ed8df43c7d714b3177b6/openprocurement/tender/competitivedialogue/utils.py#L240)):*
> ```Python
>     bid_keys = prepare_bid_identifier(data)
>     for bid_key in bid_keys:
>         if bid_key in firm_keys:
> ```

Чи не пропустить така перевірка пропозицію по лоту по якому нема допуску на участь у випадку якщо подається пропозиція на 2 лоти але тільки один з допуском?

---

*[openprocurement/tender/competitivedialogue/views/stage2/bid_document.py, line 14 \[r3\]](https://reviewable.io:443/reviews/openprocurement/openprocurement.tender.competitivedialogue/17#-KMj2BUnMTvlm5kia4eV:-KMj2BUnMTvlm5kia4eW:2117977027) ([raw file](https://github.com/openprocurement/openprocurement.tender.competitivedialogue/blob/c66437de804f517c5223ed8df43c7d714b3177b6/openprocurement/tender/competitivedialogue/views/stage2/bid_document.py#L14)):*
> ```Python
>     procurementMethodType=STAGE_2_EU_TYPE,
>     description="Competitive Dialogue Stage2 EU bidder documents")
> class CompetitiveDialogueStage2EUBidDocumentResource(TenderEUBidDocumentResource):
> ```

А як щодо financialDocuments, eligibilityDocuments і qualificationDocuments ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/openprocurement.tender.competitivedialogue/17)*

**Comment by Krokop** [comment]
Review status: 1 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[openprocurement/tender/competitivedialogue/utils.py, line 237 \[r3\]](https://reviewable.io:443/reviews/openprocurement/openprocurement.tender.competitivedialogue/17#-KMj0R7uCJodzwm9mBiH:-KMwUpzxT8klEzP_HhOh:5204897) ([raw file](https://github.com/openprocurement/openprocurement.tender.competitivedialogue/blob/c66437de804f517c5223ed8df43c7d714b3177b6/openprocurement/tender/competitivedialogue/utils.py#L237)):*
<details><summary><i>Previously, kroman0 (Roman Kozlovskyi) wrote…</i></summary>
> В цих функціях доцільніше віддавати set і перевіряти set пропозиції до set переліку з 1 стадії.
</details>
Ок

---

*[openprocurement/tender/competitivedialogue/utils.py, line 238 \[r3\]](https://reviewable.io:443/reviews/openprocurement/openprocurement.tender.competitivedialogue/17#-KMj-yoiL3nC1NjnxpUa:-KMwVHkzsNrOz6uCdXHX:5173697) ([raw file](https://github.com/openprocurement/openprocurement.tender.competitivedialogue/blob/c66437de804f517c5223ed8df43c7d714b3177b6/openprocurement/tender/competitivedialogue/utils.py#L238)):*
<details><summary><i>Previously, kroman0 (Roman Kozlovskyi) wrote…</i></summary>
> можливо краще використати self.request.validated['bid']?
</details>
Ok

---

*[openprocurement/tender/competitivedialogue/utils.py, line 240 \[r3\]](https://reviewable.io:443/reviews/openprocurement/openprocurement.tender.competitivedialogue/17#-KMj1-hKAh_VAZMviYqf:-KMwZeKMnpyIGLi5teDX:711796599) ([raw file](https://github.com/openprocurement/openprocurement.tender.competitivedialogue/blob/c66437de804f517c5223ed8df43c7d714b3177b6/openprocurement/tender/competitivedialogue/utils.py#L240)):*
<details><summary><i>Previously, kroman0 (Roman Kozlovskyi) wrote…</i></summary>
> Чи не пропустить така перевірка пропозицію по лоту по якому нема допуску на участь у випадку якщо подається пропозиція на 2 лоти але тільки один з допуском?
</details>
Якщо, тендер має 2 лоти, та учасник хоче створити пропозицію на 2 лоти, ось які 2 сети ми отримаємо. Після порівнняння цих сетів ми побачемо, що учасник не має право створювати пропозицію на 2 лоти.

BIDS KEYS set(['00137256_UA-EDR_75590407f46f4ee79fdaa9d126215c23', '00137256_UA-EDR_75510407f46f4ee79fdaa9d126215c23'])
FIRMS KEYS set(['00137256_UA-EDR_75590407f46f4ee79fdaa9d126215c23', '37405111_UA-EDR_75590407f46f4ee79fdaa9d126215c23'])

---

*[openprocurement/tender/competitivedialogue/views/stage2/bid_document.py, line 14 \[r3\]](https://reviewable.io:443/reviews/openprocurement/openprocurement.tender.competitivedialogue/17#-KMj2BUnMTvlm5kia4eV:-KMwqLxQP_x7nL4hteD7:1510103746) ([raw file](https://github.com/openprocurement/openprocurement.tender.competitivedialogue/blob/c66437de804f517c5223ed8df43c7d714b3177b6/openprocurement/tender/competitivedialogue/views/stage2/bid_document.py#L14)):*
<details><summary><i>Previously, kroman0 (Roman Kozlovskyi) wrote…</i></summary>
> А як щодо financialDocuments, eligibilityDocuments і qualificationDocuments ?
</details>
Додав financialDocuments, eligibilityDocuments і qualificationDocuments.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/openprocurement.tender.competitivedialogue/17)*

**Comment by kroman0** [comment]
Reviewed 1 of 2 files at r4.
Review status: 2 of 3 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/openprocurement.tender.competitivedialogue/17)*

**Comment by kroman0** [comment]
Reviewed 1 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/openprocurement.tender.competitivedialogue/17)*

**Pull request merged**
