### PR TITLE
For code review

### PR DESCRIPTION
**Pull request by gorserg**
@myroslav 
Початкова версія для code review 
Відповідей не дочекалися (у групі Open Procurement Development задавали), тому деякі рішення прийняли на власний розсуд.
Розробку продовжуємо в master-гілці, цей бранч формально зріз того що є на даний момент

---
This change is [Reviewable](https://reviewable.io/reviews/openprocurement/openprocurement.tender.competitivedialogue/2)

### CODE REVIEW

**Comment by kroman0** [comment]
Review status: 0 of 25 files reviewed at latest revision, 4 unresolved discussions.

---

*[README.md, line 5 \[r6\]](https://reviewable.io:443/reviews/openprocurement/openprocurement.tender.competitivedialogue/2#-KJfLIqSz2ujT0JGzNlx:-KJfLIqSz2ujT0JGzNly:-1082690603) ([raw file](https://github.com/openprocurement/openprocurement.tender.competitivedialogue/blob/aaabf805d69ea912a2e71478bc09ea1be1ab8428/README.md#L5)):*
> ```Markdown
> [Gitter](https://gitter.im/openprocurement/openprocurement.tender.competitivedialogue?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)
> 
> [Coverage Status](https://coveralls.io/github/gorserg/openprocurement.tender.competitivedialogue?branch=master)
> ```

Тут мало б бути https://coveralls.io/repos/github/openprocurement/openprocurement.tender.competitivedialogue/badge.svg

---

*[requirements.txt, line 50 \[r6\]](https://reviewable.io:443/reviews/openprocurement/openprocurement.tender.competitivedialogue/2#-KJfLfZpMi0TaJoBmD1I:-KJfLfZpMi0TaJoBmD1J:1965389007) ([raw file](https://github.com/openprocurement/openprocurement.tender.competitivedialogue/blob/aaabf805d69ea912a2e71478bc09ea1be1ab8428/requirements.txt#L50)):*
> ```
> git+https://github.com/openprocurement/rfc6266.git
> -e git+https://github.com/openprocurement/openprocurement.api.git@master#egg=openprocurement.api 
> -e git+https://github.com/openprocurement/openprocurement.tender.openua.git@master#egg=openprocurement.tender.openua
> ```

Напевно ще бракує openprocurement.tender.openeu

---

*[openprocurement/tender/competitivedialogue/models.py, line 38 \[r6\]](https://reviewable.io:443/reviews/openprocurement/openprocurement.tender.competitivedialogue/2#-KJfNIOnGBLi4UzKD4ID:-KJfNIOnGBLi4UzKD4IE:106425183) ([raw file](https://github.com/openprocurement/openprocurement.tender.competitivedialogue/blob/aaabf805d69ea912a2e71478bc09ea1be1ab8428/openprocurement/tender/competitivedialogue/models.py#L38)):*
> ```Python
>     'edit_complete': whitelist(),
>     'edit_unsuccessful': whitelist(),
>     'edit_cancelled': whitelist(),
> ```

Бракує ролей для 'active.pre-qualification' і 'active.pre-qualification.stand-still'

---

*[openprocurement/tender/competitivedialogue/models.py, line 62 \[r6\]](https://reviewable.io:443/reviews/openprocurement/openprocurement.tender.competitivedialogue/2#-KJfN7dLjb3SYGwV-g0j:-KJfN7dLjb3SYGwV-g0k:-2138007472) ([raw file](https://github.com/openprocurement/openprocurement.tender.competitivedialogue/blob/aaabf805d69ea912a2e71478bc09ea1be1ab8428/openprocurement/tender/competitivedialogue/models.py#L62)):*
> ```Python
>     status = StringType(choices=['draft', 'active.tendering', 'active.pre-qualification',
>                                  'active.pre-qualification.stand-still', 'active.qualification',
>                                  'active.awarded', 'complete', 'cancelled', 'unsuccessful'],
> ```

'active.qualification' і 'active.awarded' в ці процедурі не передбачені

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/openprocurement.tender.competitivedialogue/2)*

**Comment by kroman0** [comment]
Reviewed 10 of 17 files at r1, 1 of 3 files at r5.
Review status: 11 of 25 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/openprocurement.tender.competitivedialogue/2)*

**Comment by gorserg** [comment]
*[README.md, line 5 \[r6\]](https://reviewable.io:443/reviews/openprocurement/openprocurement.tender.competitivedialogue/2#-KJfLIqSz2ujT0JGzNlx:-KJifzxpu_orBMS4yqbc:-499146009) ([raw file](https://github.com/openprocurement/openprocurement.tender.competitivedialogue/blob/aaabf805d69ea912a2e71478bc09ea1be1ab8428/README.md#L5)):*
<details><summary><i>Previously, kroman0 (Roman Kozlovskyi) wrote…</i></summary>
> Тут мало б бути https://coveralls.io/repos/github/openprocurement/openprocurement.tender.competitivedialogue/badge.svg
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/openprocurement.tender.competitivedialogue/2)*

**Comment by gorserg** [comment]
*[requirements.txt, line 50 \[r6\]](https://reviewable.io:443/reviews/openprocurement/openprocurement.tender.competitivedialogue/2#-KJfLfZpMi0TaJoBmD1I:-KJig32lT4-eVKkDKXQo:-499146009) ([raw file](https://github.com/openprocurement/openprocurement.tender.competitivedialogue/blob/aaabf805d69ea912a2e71478bc09ea1be1ab8428/requirements.txt#L50)):*
<details><summary><i>Previously, kroman0 (Roman Kozlovskyi) wrote…</i></summary>
> Напевно ще бракує openprocurement.tender.openeu
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/openprocurement.tender.competitivedialogue/2)*

**Comment by gorserg** [comment]
*[openprocurement/tender/competitivedialogue/models.py, line 38 \[r6\]](https://reviewable.io:443/reviews/openprocurement/openprocurement.tender.competitivedialogue/2#-KJfNIOnGBLi4UzKD4ID:-KJig5yST-iUz7TummP8:-499146009) ([raw file](https://github.com/openprocurement/openprocurement.tender.competitivedialogue/blob/aaabf805d69ea912a2e71478bc09ea1be1ab8428/openprocurement/tender/competitivedialogue/models.py#L38)):*
<details><summary><i>Previously, kroman0 (Roman Kozlovskyi) wrote…</i></summary>
> Бракує ролей для 'active.pre-qualification' і 'active.pre-qualification.stand-still'
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/openprocurement.tender.competitivedialogue/2)*

**Comment by gorserg** [comment]
*[openprocurement/tender/competitivedialogue/models.py, line 62 \[r6\]](https://reviewable.io:443/reviews/openprocurement/openprocurement.tender.competitivedialogue/2#-KJfN7dLjb3SYGwV-g0j:-KJihKuGv4wemQeniOOL:-499146009) ([raw file](https://github.com/openprocurement/openprocurement.tender.competitivedialogue/blob/aaabf805d69ea912a2e71478bc09ea1be1ab8428/openprocurement/tender/competitivedialogue/models.py#L62)):*
<details><summary><i>Previously, kroman0 (Roman Kozlovskyi) wrote…</i></summary>
> 'active.qualification' і 'active.awarded' в ці процедурі не передбачені
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/openprocurement.tender.competitivedialogue/2)*

**Comment by kroman0** [comment]
Reviewed 3 of 17 files at r1, 1 of 5 files at r2, 1 of 3 files at r5, 1 of 7 files at r6, 6 of 13 files at r7, 3 of 8 files at r9, 3 of 7 files at r10.
Review status: 29 of 33 files reviewed at latest revision, 4 unresolved discussions.

---

*[openprocurement/tender/competitivedialogue/models.py, line 38 \[r6\]](https://reviewable.io:443/reviews/openprocurement/openprocurement.tender.competitivedialogue/2#-KJfNIOnGBLi4UzKD4ID:-KJjVn4OlJVrVUuyxtvn:1645894672) ([raw file](https://github.com/openprocurement/openprocurement.tender.competitivedialogue/blob/aaabf805d69ea912a2e71478bc09ea1be1ab8428/openprocurement/tender/competitivedialogue/models.py#L38)):*
<details><summary><i>Previously, gorserg (Sergey Gorobets) wrote…</i></summary>
> Done.
</details>
і ще "edit_*"

---

*[openprocurement/tender/competitivedialogue/models.py, line 62 \[r6\]](https://reviewable.io:443/reviews/openprocurement/openprocurement.tender.competitivedialogue/2#-KJfN7dLjb3SYGwV-g0j:-KJjWZwkXRdpr1BjKhXY:1890996733) ([raw file](https://github.com/openprocurement/openprocurement.tender.competitivedialogue/blob/aaabf805d69ea912a2e71478bc09ea1be1ab8428/openprocurement/tender/competitivedialogue/models.py#L62)):*
<details><summary><i>Previously, gorserg (Sergey Gorobets) wrote…</i></summary>
> Done.
</details>
choices в полі status потрібно підчистити

---

*[openprocurement/tender/competitivedialogue/tests/base.py, line 239 \[r10\]](https://reviewable.io:443/reviews/openprocurement/openprocurement.tender.competitivedialogue/2#-KJjYKl915WvXd9svqwX:-KJjYKl915WvXd9svqwY:1751597626) ([raw file](https://github.com/openprocurement/openprocurement.tender.competitivedialogue/blob/26acb84796ba95f5160a627043c2e33a275febe7/openprocurement/tender/competitivedialogue/tests/base.py#L239)):*
> ```Python
>                 }
>             })
>         elif status == 'active.qualification':
> ```

Ті статути яких в процедурі нема краще прибрати

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/openprocurement.tender.competitivedialogue/2)*

**Comment by kroman0** [comment]
Reviewed 2 of 7 files at r10.
Review status: 31 of 33 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/openprocurement.tender.competitivedialogue/2)*

**Comment by gorserg** [comment]
*[openprocurement/tender/competitivedialogue/models.py, line 62 \[r6\]](https://reviewable.io:443/reviews/openprocurement/openprocurement.tender.competitivedialogue/2#-KJfN7dLjb3SYGwV-g0j:-KJq74-xS1qiv_dsrWP-:-499146009) ([raw file](https://github.com/openprocurement/openprocurement.tender.competitivedialogue/blob/aaabf805d69ea912a2e71478bc09ea1be1ab8428/openprocurement/tender/competitivedialogue/models.py#L62)):*
<details><summary><i>Previously, kroman0 (Roman Kozlovskyi) wrote…</i></summary>
> choices в полі status потрібно підчистити
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/openprocurement.tender.competitivedialogue/2)*

**Comment by gorserg** [comment]
*[openprocurement/tender/competitivedialogue/models.py, line 38 \[r6\]](https://reviewable.io:443/reviews/openprocurement/openprocurement.tender.competitivedialogue/2#-KJfNIOnGBLi4UzKD4ID:-KJq77GhAI6Fqr6GF1WW:-499146009) ([raw file](https://github.com/openprocurement/openprocurement.tender.competitivedialogue/blob/aaabf805d69ea912a2e71478bc09ea1be1ab8428/openprocurement/tender/competitivedialogue/models.py#L38)):*
<details><summary><i>Previously, kroman0 (Roman Kozlovskyi) wrote…</i></summary>
> і ще "edit_*"
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/openprocurement.tender.competitivedialogue/2)*

**Comment by gorserg** [comment]
*[openprocurement/tender/competitivedialogue/tests/base.py, line 239 \[r10\]](https://reviewable.io:443/reviews/openprocurement/openprocurement.tender.competitivedialogue/2#-KJjYKl915WvXd9svqwX:-KJoAILKriUeq2wFqB1G:-1046844697) ([raw file](https://github.com/openprocurement/openprocurement.tender.competitivedialogue/blob/26acb84796ba95f5160a627043c2e33a275febe7/openprocurement/tender/competitivedialogue/tests/base.py#L239)):*
<details><summary><i>Previously, kroman0 (Roman Kozlovskyi) wrote…</i></summary>
> Ті статути яких в процедурі нема краще прибрати
</details>
Статус active.auction поки залишили, так як багато тестів на нього зав'язані, зараз важкувато "випиляти" все лишнє відразу, потім приберемо

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/openprocurement.tender.competitivedialogue/2)*

**Comment by gorserg** [comment]
внесені додаткові зміни згідно отриманих сьогодні відповідей, також добавлена перший варіант реалізації bridge

**Comment by kroman0** [comment]
Тоді беремо цей код за основу.

<details><summary><i>Previously, coveralls wrote…</i></summary>
> 
> [Coverage Status](https://coveralls.io/builds/6568642)
> 
> Changes Unknown when pulling **d4b6fb8fa572b1a9e68c1834c19218e0f83c50e9 on gorserg:for_code_review** into ** on openprocurement:master**.
> 
</details>


---

Reviewed 2 of 3 files at r11, 10 of 12 files at r12, 1 of 2 files at r13.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/openprocurement.tender.competitivedialogue/2#-:-KK7u9aCIdnvqF7cNZ8h:-1769105088)*

**Pull request merged**
