### PR TITLE
open deliveryDate

### PR DESCRIPTION
**Pull request by Krokop**
Замовник може також редагувати deliveryDate

---
This change is [Reviewable](https://reviewable.io/reviews/openprocurement/openprocurement.tender.competitivedialogue/52)

### CODE REVIEW

**Comment by kroman0** [comment]
В тендері нема поля deliveryDate + потрібні тести

**Comment by Krokop** [comment]
Дозволив редагувати deliveryDate в items, покрив тестами https://github.com/openprocurement/openprocurement.tender.competitivedialogue/pull/52/files#diff-ce9c1072042628171d83b881b4c0f805L937 
https://github.com/openprocurement/openprocurement.tender.competitivedialogue/pull/52/files#diff-ce9c1072042628171d83b881b4c0f805R2090

**Comment by Krokop** [comment]
Додав тести для  tender другого етапу UA, виправив помилки в EU

**Comment by kroman0** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[openprocurement/tender/competitivedialogue/models.py, line 331 \[r2\]](https://reviewable.io:443/reviews/openprocurement/openprocurement.tender.competitivedialogue/52#-KOeXY9s14MpUNa1zr_s:-KOeXY9s14MpUNa1zr_t:b-gs5n3q) ([raw file](https://github.com/openprocurement/openprocurement.tender.competitivedialogue/blob/226e310b45a5e35d83cb705ff02b2028d548264b/openprocurement/tender/competitivedialogue/models.py#L331)):*
> ```Python
> 
>     class Options:
>         roles = {'edit_active.tendering': whitelist('endDate')}
> ```

А чому не можна поміняти startDate? Якщо встановлено startDate на 1 етапі то в 2 можуть виникнути проблеми з послідовністю дат періоду

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/openprocurement.tender.competitivedialogue/52)*

**Comment by Krokop** [comment]
Згоден, відкрив startDate

**Comment by Krokop** [comment]
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[openprocurement/tender/competitivedialogue/models.py, line 331 \[r2\]](https://reviewable.io:443/reviews/openprocurement/openprocurement.tender.competitivedialogue/52#-KOeXY9s14MpUNa1zr_s:-KOedViMoJ0z863p4lwy:bnu37ob) ([raw file](https://github.com/openprocurement/openprocurement.tender.competitivedialogue/blob/226e310b45a5e35d83cb705ff02b2028d548264b/openprocurement/tender/competitivedialogue/models.py#L331)):*
<details><summary><i>Previously, kroman0 (Roman Kozlovskyi) wrote…</i></summary>
> А чому не можна поміняти startDate? Якщо встановлено startDate на 1 етапі то в 2 можуть виникнути проблеми з послідовністю дат періоду
</details>
Відкрив startDate

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/openprocurement.tender.competitivedialogue/52)*

**Comment by kroman0** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/openprocurement.tender.competitivedialogue/52)*

**Pull request merged**
